### ISSUE TITLE
baseUrl配置不科学

### ISSUE THREAD

**Issue by taadis** [lampo1024/DncZeus#12]
RT.

``` json
// 现有配置为
baseUrl: {
    dev: 'http://localhost:54321/api/v1/',
    pro: 'http://localhost:54321/api/v1/'
  }
```
这里的 `/api/v1` 不具备共性,不应该放到 `baseUrl` 里,

举些栗子:

- 新增的 api 不以 `api/v1` 为前缀的怎么办?另写一个 axios 的封装,明显不合理
- 有些接口发布后是api直接用二级域名 `http://api.some.com`,这个时候 `baseUrl=http://api.some.com/api/v1`,看着就不有爱...
- ...
- 总而言之...`/api/v1`不应该放到 `baseUrl` 里

iview-admin 本身给的例子也是真正具备共性的 [baseUrl](https://github.com/iview/iview-admin/blob/master/src/config/index.js)

**Comment by lampo1024** [comment]
@taadis 已 [改进请求资源的前缀配置方案](https://github.com/lampo1024/DncZeus/commit/29c924db0113797c897d4210ffe062fea33ca990)，具体使用方法 [请参考这里](https://github.com/lampo1024/DncZeus/commit/29c924db0113797c897d4210ffe062fea33ca990#diff-280005149f283ce7a6bb2d73693e0f68)
如果你有更好的方案，也欢迎反馈，交流
