### ISSUE TITLE
用户退出登录后重新登录标签页仍然保持退出前打开状态

### ISSUE THREAD

**Issue by lincjsun** [lampo1024/DncZeus#15]
1).用户退出登录后重新登录;2).用户退出登录后切换用户登录
以上这两种情况下标签页仍然保持上一用户登录时的打开状态

**Comment by lampo1024** [comment]
退出登录时清除所有已打开的选项卡：[Close all tabs when logout](https://github.com/lampo1024/DncZeus/commit/3c148fb7522fe0a8505bc2a68e33ab3e8f11b17b)
