### ISSUE TITLE
项目对MySQL的支持略为粗糙

### ISSUE THREAD

**Issue by Bingjian-Zhu** [lampo1024/DncZeus#23]
如题，我已经把代码改成用MySQL的了，主键全改成自增ID，数据库也进行了优化，同时修改了测试发现的Bug

**Comment by lampo1024** [comment]
感谢你的反馈，确实项目对MySQL的支持是比较弱的，目前的MySQL也是另外一位开发者帮助实现的，如果你对项目感兴趣，也欢迎提交你的PR，我们可以共同维护。

**Comment by Bingjian-Zhu** [comment]
可以，让我整理下代码再提交
