### ISSUE TITLE
添加菜单使用超级管理员登陆 登陆后点击左侧菜单在右侧显示正常  按下F5刷新后 页面空白不现实问题。

### ISSUE THREAD

**Issue by KaiFaZhangHao123** [lampo1024/DncZeus#24]
添加菜单使用超级管理员登陆 登陆后点击左侧菜单在右侧显示正常  按下F5刷新后 页面空白不现实问题。

**Comment by KaiFaZhangHao123** [comment]
![image](https://user-images.githubusercontent.com/46866160/56074384-fb80ea80-5de3-11e9-9281-daf0a6c07ed8.png)
刷新后
![image](https://user-images.githubusercontent.com/46866160/56074393-1f443080-5de4-11e9-9b96-348d71c9adbf.png)

**Comment by KaiFaZhangHao123** [comment]
点击页面全屏按下 F5 或者 点击右键刷新就这样了

**Comment by lampo1024** [comment]
你看一下浏览器控制台有没有报错？

**Comment by KaiFaZhangHao123** [comment]
添加什么 cms 换成了web就没问题 是否有关键字过滤？？

**Comment by lampo1024** [comment]
应该不会吧
