### ISSUE TITLE
能否写下项目规划，那些功能未完成那些已完成！

### ISSUE THREAD

**Issue by JL-Code** [lampo1024/DncZeus#3]
能否写下项目规划，那些功能未完成那些已完成！
能否介绍下以下两种机制的设计
1. 令牌的作废机制
2. 令牌的过期机制

**Comment by lampo1024** [comment]
感谢你对DncZeus项目的关注和支持，目前正在完善第一版的文档，计划在下月初整理DncZeus项目的后期开发规划。
