### ISSUE TITLE
登陆接口 报异常怎么解决

### ISSUE THREAD

**Issue by wanglaing** [lampo1024/DncZeus#32]
user = _dbContext.DncUser.FirstOrDefault(x => x.LoginName == username.Trim());
![image](https://user-images.githubusercontent.com/22931973/61110895-e555f980-a4ba-11e9-923d-e2ca30b77171.png)

**Comment by lampo1024** [comment]
建议你“查看详细信息”，单从你上面的截图看不出更多有用的可以解决问题的信息。
