### ISSUE TITLE
编译缺少fonts目录

### ISSUE THREAD

**Issue by redochen** [lampo1024/DncZeus#37]
ERROR  Failed to compile with 1 errors                                                                                     9:03:36 PM
 error  in ./src/index.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './fonts/ionicons.svg?v=3.0.0' in 'E:\Work\C#\Demo\DncZeus\DncZeus.App\src'

**Comment by Create-Peace** [comment]
这个问题怎么解决的 ？

**Comment by focusxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
