### ISSUE TITLE
是否支持用户分组、角色分组、权限分组？

### ISSUE THREAD

**Issue by zmsoft** [lampo1024/DncZeus#42]
楼主您好，看过您的项目，感觉写的非常好，对我帮助非常大，在学习RBAC的时候，使我更加能理解这种基于用户权限控制的设计思想，如果要是能够再支持用户分组、角色分组、权限分组那就太好了。

**Comment by lampo1024** [comment]
> 
> 
> 楼主您好，看过您的项目，感觉写的非常好，对我帮助非常大，在学习RBAC的时候，使我更加能理解这种基于用户权限控制的设计思想，如果要是能够再支持用户分组、角色分组、权限分组那就太好了。

非常感谢你的支持！！！
项目没有你所说的几个分组功能，项目是开源的，你可以根据自己需要进行扩展。
