### ISSUE TITLE
更新3.1 api 之后编辑用户，出现这个错误。

### ISSUE THREAD

**Issue by chenshican** [lampo1024/DncZeus#46]
更新3.1 api 之后编辑用户，出现这个错误：

usercontroller
public IActionResult Edit(Guid guid)
位置：response.SetData(_mapper.Map<DncUser, UserEditViewModel>(entity));

错误提示：AutoMapper.AutoMapperMappingException:“Missing type map configuration or unsupported mapping.”

**Comment by lampo1024** [comment]
在映射配置文件中：
https://github.com/lampo1024/DncZeus/blob/master/DncZeus.Api/Configurations/MappingProfile.cs
添加这个关系映射

```
CreateMap<DncUser,UserEditViewModel>();
```
