### ISSUE TITLE
发现一个排序的BUG

### ISSUE THREAD

**Issue by chenshican** [lampo1024/DncZeus#49]
查询参数：stores.user.query.sort当中，用的是变量名是：direct，但column on change当中，是赋值变量：direction；这个是bug吧？另外，sort的数据类型是数组，sortchange事件当中并没有当数组来赋值，导致了一直都是传漏参数，因此一直是前端排序，并没有服务器端排序。

            sort: [
              {
                **direct: "DESC",**
                field: "Guid"
              }
            ]

    handleSortChange(column) {
      **this.stores.user.query.sort.direction = column.order;**
      this.stores.user.query.sort.field = column.key;
      this.loadPostList();
    },

**Comment by lampo1024** [comment]
请根据你的实际需求场景自行修正
