### ISSUE TITLE
可以问下，这个项目如何实现跨域请求呢

### ISSUE THREAD

**Issue by Doub1eH** [lampo1024/DncZeus#51]

**Comment by lampo1024** [comment]
后端Api项目去配置Cors即可，如下图：

![01](https://user-images.githubusercontent.com/3262079/81470107-7735ac80-921b-11ea-8c44-021c491294fd.png)

![02](https://user-images.githubusercontent.com/3262079/81470106-76047f80-921b-11ea-82e8-46a9c227f580.png)
