### ISSUE TITLE
建议前后端2个项目分开存放哦

### ISSUE THREAD

**Issue by taadis** [lampo1024/DncZeus#7]
RT.

**Comment by lampo1024** [comment]
你的意思是前后端分为两个仓库？给我十万个这样做的理由。。。

**Comment by taadis** [comment]
说说我的建议：

前后端分离本身就意味着技术栈上的完全不同,本身就应该分开了

- 后端: `.NET Core & EntityFrameworkCore & AutoMapper & so on`
- 前端: `nodejs & vue全家桶 & mockjs & so on `

省略其他9.9W个理由...

**Comment by lampo1024** [comment]
技术栈是分开的，前后端的项目也是分开的，只是在同一个仓库里面，这样方便仓库的管理和版本更新。

**Comment by taadis** [comment]
我想说的也是这个,只是建议而已.

方便其他小伙伴*只*看到自己前/后端相关的内容,保持相对的独立和整洁性,

举个栗子:

- 一位前端小伙伴fork下项目,只是参考/贡献/其他前端的内容,结果下来还有一堆后端的内容...
- 一位后端小伙伴fork下项目,只是参考/贡献/其他后端的内容,结果下来还有一堆前端的内容...
- ~~尽管分了2个文件夹~~

**Comment by taadis** [comment]
前后端分离从人的角度而言:

- 前端小伙伴的内心OS:除了后端接口,我不想听/看/...任何和后端相关的内容
- 后端小伙伴的内心OS:除了前端对接,我不想听/看/...任何和前端相关的内容

**Comment by taadis** [comment]
饿...只是说说我的想法,建议而已,勿介.

**Comment by lampo1024** [comment]
有建议是很好的，也非常感谢你的建议。
