### ISSUE TITLE
创建用户时会报错

### ISSUE THREAD

**Issue by taadis** [lampo1024/DncZeus#8]
RT.

![default](https://user-images.githubusercontent.com/16029681/52697507-8e500500-2fac-11e9-820a-aec2400596dd.png)

**Comment by lampo1024** [comment]
建议打开浏览器控制台的"网络请求"看一下，具体是什么错误。

**Comment by taadis** [comment]
[https://dnczeus.codedefault.com](https://dnczeus.codedefault.com) 在线体验创建用户就报错,所以反馈下...

**Comment by lampo1024** [comment]
好的，感谢反馈

**Comment by taadis** [comment]
创建用户请求:

![default](https://user-images.githubusercontent.com/16029681/52702498-3ff43380-2fb7-11e9-96d9-1a6a674b9328.png)

响应:

![default](https://user-images.githubusercontent.com/16029681/52702521-4da9b900-2fb7-11e9-8f76-c8397270e5ed.png)

**Comment by taadis** [comment]
@lampo1024

**Comment by taadis** [comment]
嘿嘿,我补个链接,方便查看 [bugfix](https://github.com/lampo1024/DncZeus/commit/94c487aead797d4dc86d1bbc06de60e28c072297)
