### ISSUE TITLE
vue启动报错 Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by mirtnt** [lampo1024/DncZeus#80]
似乎是nodejs版本更新openssl造成的错误
"scripts": {
    "serve": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
}
使用 npm run serve后成功启动

**Comment by focusxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
