### ISSUE TITLE
还原前端依赖失败

### ISSUE THREAD

**Issue by hehetiger** [lampo1024/DncZeus#84]
![企业微信截图_20240822104457](https://github.com/user-attachments/assets/f315a2ec-57ae-4627-b559-f6f27c609fc8)
报错后卡住不动了

npm verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick - [NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet
npm verbose audit error     at C:\Program Files\nodejs\node_global\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
npm verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verbose audit error     at async [getReport] (C:\Program Files\nodejs\node_global\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:336:21)
npm verbose audit error     at async AuditReport.run (C:\Program Files\nodejs\node_global\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:106:19) {
npm verbose audit error   headers: [Object: null prototype] {
npm verbose audit error     server: [ 'Tengine' ],
npm verbose audit error     date: [ 'Thu, 22 Aug 2024 02:27:06 GMT' ],
npm verbose audit error     'content-type': [ 'application/json' ],
npm verbose audit error     'transfer-encoding': [ 'chunked' ],
npm verbose audit error     connection: [ 'keep-alive' ],
npm verbose audit error     'strict-transport-security': [ 'max-age=5184000' ],
npm verbose audit error     via: [ 'kunlun8.cn5864[,404666]' ],
npm verbose audit error     'timing-allow-origin': [ '*' ],
npm verbose audit error     eagleid: [ 'b6284e8a17242936262327904e' ],
npm verbose audit error     'x-fetch-attempts': [ '1' ]
npm verbose audit error   },
npm verbose audit error   statusCode: 404,
npm verbose audit error   code: 'E404',
npm verbose audit error   method: 'POST',
npm verbose audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
npm verbose audit error   body: {
npm verbose audit error     error: '[NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet'
npm verbose audit error   },
npm verbose audit error   pkgid: undefined
npm verbose audit error }

**Comment by focusxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
